### ISSUE TITLE
Question on subnets tagging

### ISSUE THREAD

**Issue by dzsessona** [zillowgroup/kong-terraform#1]
Hello, would love to deploy kong on aws with terraform, but don't understand the convention of what is looking in the "Type" tag of the subnets. Which values should i put? 

Thank you

**Comment by DennoVonDiesel** [comment]
You will need to use AWS tag called "Type" to specify public and private subnets.  Typically this is just:

Type = private

or

Type = public

Then the module will know which subnets to use/select for instances and load balancers. Let me know if this helps!

**Comment by DennoVonDiesel** [comment]
Additionally, the tag used on the subnets is configurable. Many open source modules for VPC's use the Tag key "Tier" which is now the default.  However, you can continue to tag subnets with the "Type" tag and specify subnet_tag = "Type" and values of private and public associated with your subnets respectively.
