### ISSUE TITLE
Terraform Plan Results in Errors

### ISSUE THREAD

**Issue by matty1979** [zillowgroup/kong-terraform#2]
Creating a main.tf and running terraform plan -out kong.plan results in following errors. 

```
Error: Missing required argument
  on main.tf line 6, in module "kong":
   6: module "kong" {
The argument "enable_ee" is required, but no definition was found.
Error: Unsupported argument
  on main.tf line 12, in module "kong":
  12:   ec2_ebs_optimized     = false
An argument named "ec2_ebs_optimized" is not expected here.
```

**Comment by DennoVonDiesel** [comment]
Can you provide me a copy of your main.tf? Feel free to strip out sensitive values.

**Comment by trietlam** [comment]
Not sure if I miss anything, but seems like there is no `variable "ec2_ebs_optimized" {}` declared in the project. Maybe that's why there is such error 😓

**Comment by DennoVonDiesel** [comment]
This is fixed in the latest branch: github.com/zillowgroup/kong-terraform?ref=v3.0
